### ISSUE TITLE
Allow appending of audio to other fields

### ISSUE THREAD

**Issue by nataelj** [ospalh/anki-addons#101]
Currently this addon seems to require and Audio field as a separate entity. Often that's good, but sometimes I just want to add the audio to another field. E.g., sometimes I want to hear the word when I see it too. Allowing me to append the audio to another field would make this quite easy. As it is I have to do this by adding an audio field and then moving the audio manually.

This might also be combined with the other outstanding issue about downloading a selected word.

**Comment by ospalh** [comment]
I designed it the current way deliberately.
What you should do is edit your models to add the audio fields to the sides you want. RT[FM](https://ospalh.github.io/anki-addons/Add_audio_to_card.html).

If you insist, you can add your own field in the code of your copy. Add the name to [this line](https://github.com/ospalh/anki-addons/blob/develop/downloadaudio/get_fields.py#L40).
