### ISSUE TITLE
Download audio’s  Japanesepod downloader  stopped working

### ISSUE THREAD

**Issue by chrispthompson** [ospalh/anki-addons#103]
Yesterday the add-on stopped working... when I send a request to find audio for a word, it just comes back with "nothing downloaded." 

This is happening on my laptop and on my desktop. I've deleted the add-on and reinstalled, and made sure I have a field called "Audio" on the card.

Even the most common words don't come back with any results -- 来る, 食べる, etc. This happened suddenly after no particular change in my system.

**Comment by ospalh** [comment]
I guess one of the audio sources stopped working, not the add-on per se.
Which one?

**Comment by ospalh** [comment]
That is, for which audio source did you get replies for whole sentences the day before yesterday?

**Comment by chrispthompson** [comment]
I was only using this for single words, not whole sentences (though I'd love to know how to do that if it is possible!) -- the single words were coming from japanesepod101's library of audio recordings.

**Comment by ospalh** [comment]
Well, OK. I just thought 

> 来る, 食べる

meant 「来る、食べる。」 rather than “来る”, “食べる”. My bad. I should have recognized the western comma.

**Comment by chrispthompson** [comment]
no problem! So, is there any way to check the japanesepod101 source to see if it has stopped replying recently or something? (and thanks for the help with this)

**Comment by ospalh** [comment]
Sure, go ahead and check.
I know as much as you. Less, actually, as you noticed the problem.

**Comment by chrispthompson** [comment]
How would I check that? Are you the developer?

**Comment by ospalh** [comment]
Honestly, i am not all that interested in these add-ons at the moment.
Japanesepod101 is a for-profit site that wants to sell you their Japanese language courses.
Up to now, their pronunciation files were on a publicly accessible server. They just let you download them without any checks. Maybe they finally thought that was a bad idea and shut down the server. I have no idea.
And i am in no way connected to the original site.
When the download stopped working, that may well be it with the Japanese part of this add-on. It was fun will it lasted.

**Comment by chrispthompson** [comment]
that's my guess as well, but I'd love to confirm that this is the case before I delete the add-on because this tool is immensely helpful for me and there is nothing else like it available.

So if you know of a way to confirm whether or not jpod101 has cut off public access to their server, kindly let me know. I'm sorry if this should be obvious and I just don't know to do it!

**Comment by ospalh** [comment]
I don’t really know much more than you do.
The server address that i used is set in the code here:
https://github.com/ospalh/anki-addons/blob/develop/downloadaudio/downloaders/japanesepod.py#L47
Maybe that server is only down temporarily and it will work again in a day. Maybe not.

**Comment by chrispthompson** [comment]
thanks!

**Comment by chrispthompson** [comment]
Just wanted to report that jpod101's server seemed to go back up again today, so it was only a temporary thing -- this add-on is working great again as before.

**Comment by ospalh** [comment]
OK then. Have fun.
