### ISSUE TITLE
MacMillan Stopped  [SOLVED]

### ISSUE THREAD

**Issue by hghofraniha** [ospalh/anki-addons#108]
hi,
  today download audio suddenly stopped working and just show "nothing downloaded" notification.
I also checked it by oald and googleTTs but doesn't change anything, however worked for wiktionary.

**Comment by belteshassar** [comment]
I took a quick look, but MacMillan works fine for me. As far as I can see, there have been no changes to the MacMillan website, but perhaps they've decided to test a new version in your location.

If you want to help with troubleshooting, you can take a look at the source for http://www.macmillandictionary.com/dictionary/british/<word>. Exchange <word> for the word that you are interested in.

Search for a tag with `class="sound ..."` and check that it has a `data-src-mp3` attribute that points to a valid sound file.

This is basically what the downloader code does, see https://github.com/ospalh/anki-addons/blob/develop/downloadaudio/downloaders/macmillan.py

**Comment by hghofraniha** [comment]
Thanks. After a couple of days its back and now working.
