### ISSUE TITLE
New Addon

### ISSUE THREAD

**Issue by darkzbaron** [ospalh/anki-addons#113]
Hi there, I am new in the anki addon business and I am trying to put together an addon that would open decks for me according to some rule.

The documentation is very limited and I am wondering if you can help me find out how to open a deck.

Essentially, I want my anki addon to open on startup a specific deck according to the day of the week.

Thanks for the great work anyway!

**Comment by ospalh** [comment]
I will not do your homework for you.

**Comment by darkzbaron** [comment]
OK fair enough, I was lazy... thanks for the reply. Here is the code 
import aqt
aqt.mw.col.decks.get(deck_id)
aqt.mw.moveToState("overview")
