### ISSUE TITLE
Replay button plugin shows text instead of image

### ISSUE THREAD

**Issue by woj-tek** [ospalh/anki-addons#114]
I've installed the plugin but instead of play button image it only shows `Replay` text. This happens on macOS with Anki 2.0

**Comment by omega3** [comment]
Do you use this:
https://github.com/ospalh/anki-addons/blob/develop/png_play_button.py

On Anki 2.0 I used png icon as replay button with this add-on.

Otherwise some stilling is needed according to 
https://ospalh.github.io/anki-addons/Play_button.html

**Comment by woj-tek** [comment]
I opted for using simple character instead of SVG and it works just fine (and the code is simpler and I can change colour of the symbol using CSS in anki).

**Comment by ospalh** [comment]
@omega3 : No, i don’t plan on porting the PNG version to Anki 2.1. You’d have to adapt this yourself, maybe combining parts of the new 2.1 version with parts of the old PNG version.

@woj-tek : I don’t support the Anki 2.0 add-ons any more. Sorry.

The Anki 2.1 SVG version works well enough. Everything else is SEP.
