### ISSUE TITLE
Japanese - Nothing Downloaded

### ISSUE THREAD

**Issue by weirdalsuperfan** [ospalh/anki-addons#115]
It seems that nothing is downloaded when "ja" is selected as the language. Field detection works fine, but a Nothing downloaded notification pops up when attempting to download now, no matter which of the 3 download options I select. It seems like others have had this problem recently as well.

**Comment by JhonnySalles** [comment]
I look forward to an update.
Thank you very much.

**Comment by Kosezu** [comment]
How much money do you need to be paid to fix this?

**Comment by ospalh** [comment]
Enough money to buy japanesepod101.com and then some.
I haven’t looked into this, but when they have shut down their server, or changed how it worked, my add-on will not work. It was always a bit on the parasitic side, grabbing their pronunciations without really asking – or paying – them. So if it stopped working, that’s it.

**Comment by Kosezu** [comment]
The add-on still works on Anki 2.0 but there's something not quite correct in the 2.1 version. I have everything displaying, like the menus and everything, but nothing downloads when I attempt to do so.

**Comment by okthxbye** [comment]
I would be super grateful if you could find the time to port Anki Audio Downloader to Anki 2.1. I love the 2.0 version for JapanesePod101 audio to add to my JP flashcards, the source still works perfectly. Thanks.

**Comment by alycm** [comment]
I also had the same issue as @Kosezu, this one line change fixed it for me: https://github.com/ospalh/anki-addons/pull/133 (in combination with the fixes already in https://github.com/ospalh/anki-addons/pull/119).

**Comment by ospalh** [comment]
It seems to work with @Kosezu’s fix, at least today,
