### ISSUE TITLE
Make the way the nid in "Add Note ID" is calculated optional

### ISSUE THREAD

**Issue by hgiesel** [ospalh/anki-addons#126]
[Here](https://github.com/ospalh/anki-addons/blob/b95da0aa70ff31617b1bdc3fc262ef20c0de08e6/add_note_id/__init__.py#L93) and [here](https://github.com/ospalh/anki-addons/blob/b95da0aa70ff31617b1bdc3fc262ef20c0de08e6/add_note_id/__init__.py#L85), rather than just copying the actual nid to the field, you take the nid value and subtract `15e11`. 

It says, you do it for "aesthetical purposes", but I don't really see why it's more aesthetical to do that. Would you accept a pull request making this feature optional?

**Comment by ospalh** [comment]
After the subtraction the number is shorter.
What is the harm in doing it, even if there is no benefit?

**Comment by ospalh** [comment]
Anyway, see #127
