### ISSUE TITLE
Recently not working for japanese, but worked perfectly a few days ago.

### ISSUE THREAD

**Issue by Hiwo21400** [ospalh/anki-addons#128]
Traceback (most recent call last):
  File "aqt/addons.py", line 41, in loadAddons
  File "/home/hiwo/.local/share/Anki2/addons/download_audio.py", line 21, in <module>
    import downloadaudio.conflanguage
ImportError: No module named downloadaudio.conflanguage

**Comment by ospalh** [comment]
I can’t really help you with the Anki 2.0 version.
I just pushed a changes to this module for Anki 2.1, and just published that, imperfect as it is.

**Comment by Hiwo21400** [comment]
Thanks, I will just go to a 2.1 Anki's version to temporarily add audio to my cards because it seems over add-on like Bulk isn't updated yet.

**Comment by Hiwo21400** [comment]
In 2.1 I can't open Browser when not forvo is active.By the way, throughout Japanesepod101 we can still download files: http://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kana=%E3%81%BE%E3%81%86&kanji=%E8%88%9E%E3%81%86
