### ISSUE TITLE
Change the place of button

### ISSUE THREAD

**Issue by weidongzhou1994** [ospalh/anki-addons#131]
This plugin is very good.  But I want to change the place of button like this:
![image](https://user-images.githubusercontent.com/40510496/65299904-036b6480-dba4-11e9-8cfa-e24fe1e1d2b5.png)

**Comment by ospalh** [comment]
Which add-on? There are a lot of them here.
I presume “[Replay buttons on card](https://ospalh.github.io/anki-addons/Play_button.html)”.
Where you place the replay button is up to you. Use the card template editor to put it where you want it. Use a special audio field if you have to.
