### ISSUE TITLE
Cannot replay from the start sometimes if a field has many audio clips

### ISSUE THREAD

**Issue by nlpsuge** [ospalh/anki-addons#132]
Hi,
I've created a field named 'Audio', and this field has several audio clips, like:

Field name: Audio
Content in this field: [sound:xxx-1.mp3][sound:xxx2.mp3][sound:xxx3.mp3][sound:xxx4.mp3]

When audios of this field is playing, pressing 'r' only make the replay from a clip in this field, but not from the start.

For example:
When 'xxx2.mp3' is playing, press 'r', then the xxx2.mp3 will be replayed, or maybe the xxx-1.mp3 will be played.

And furthermore the previous one will not be replayed.

Anki version:
Version 2.1.15 (442df9d6)
Qt 5.12.5 PyQt 5.13.1

This happens recent weeks or little longer.

**Comment by ospalh** [comment]
Which of my add-ons do you think is to blame, and why do you think that?
What happens when you start Anki with add-ons deactivated?

**Comment by nlpsuge** [comment]
I also think this issue is irrelevant to any of your add-ons, I sorry for disturbing you. And I'll post this issue to a proper place and close it.

This issue should be a bug of Anki itself.
