### ISSUE TITLE
make note-id a real uuid

### ISSUE THREAD

**Issue by boydkelly** [ospalh/anki-addons#139]
Would be nice to see a 'real' uuid there.   I add them in a spreadsheet and it doesn't appear to break anything

**Comment by ospalh** [comment]
I ges i forgot to upload the newest version.

**Comment by ospalh** [comment]
Then again as Anki didn’t install all of the standard Python libraries, i would hav to check if uuid is part of them that you do get, and i cba.
If you check the code, i did add code to use uuids and didn’t upload it.

**Comment by boydkelly** [comment]
Awesome!   You made my day!   Can you not upload this to the anki.net site?   I notice there the last version is from 2017.

**Comment by ospalh** [comment]
Can’t you just use it from here? I’m not really working on this any more and don’t want to upload a non-working version.
https://github.com/ospalh/anki-addons/tree/develop/add_note_id

**Comment by ospalh** [comment]
OK. After a quick check on my Mac, it looks like Python’s uuid package is available.
You can go and get the newest version, 2.1.0, from the Anki add-on download site.
