### ISSUE TITLE
Unnormalize doesn't work on recent Anki

### ISSUE THREAD

**Issue by zelenij** [ospalh/anki-addons#41]
On the latest Anki I am getting this error message:

Traceback (most recent call last):
  File "/path/to/user-home/Anki/addons/unnormalize.py", line 71, in unnormalize_files
    media_in_col = mw.col.media.allMedia()
AttributeError: 'MediaManager' object has no attribute 'allMedia'

**Comment by ospalh** [comment]
Please reopen when you still have problems with actual files.
