### ISSUE TITLE
The DownloadEntry breaks the audio processor

### ISSUE THREAD

**Issue by ospalh** [ospalh/anki-addons#51]
@bastik’s addition of the `DownloadEntry` class, #49, breaks the audio processor. When you have pysox and pydub installed, the audio files do get normalized and converted to flac, and then are copied to the *empty file name* in the audio folder.

**Comment by ospalh** [comment]
This does not affect most people. But it does me. So :angry:

**Comment by ospalh** [comment]
I think i have found it, so relax (or push quickly).

**Comment by ospalh** [comment]
Fixed, 388db932c

**Comment by bastik** [comment]
Thanks for fixing this bug, I probably should have tested the normalization code as well.

**Comment by ospalh** [comment]
It was hard to find through testing on a normal system, so missing that wasn’t too surprising. It only materialized with [pysox](https://pypi.python.org/pypi/pysox/0.3.6.alpha) installed, and that has apparently been abandoned in alpha phase. (And pyDub, but that is called “stable”.)
