### ISSUE TITLE
Download audio no longer find Merriam Wester audio files

### ISSUE THREAD

**Issue by Xiao-Sun** [ospalh/anki-addons#55]
No longer find Merriam Wester audio files.

**Comment by ospalh** [comment]
Looks like MW changed the look of their web site.
I am currently reworking the DA add-on anyway. I'll take a look at the MW code as well.

**Comment by Supermemo** [comment]
Do you know where to bulk download all MW audio files? Or open the sound.cmp file that's found in MW dictionary software?

**Comment by ospalh** [comment]
I am not doing [bulk downloads](https://ospalh.github.io/anki-addons/Download%20audio.html) on purpose.

And i am not using any MW *software*. As the name *downloader* says, i am using their online dictionary.

**Comment by ospalh** [comment]
Much easier than i thought.
I will roll out a fixed version some time soon.

**Comment by Supermemo** [comment]
cool, let us know when you roll it out.

**Comment by Xiao-Sun** [comment]
Can I choose to have audio download only from Merriam Webster?

Or, at least have all the audios unticked by default. It is laborious that I have to unticked 20 boxes to download an audio.

[URL=http://s1150.photobucket.com/user/FinancialWar/media/Capture_zpsasuitutq.png.html][IMG]http://i1150.photobucket.com/albums/o615/FinancialWar/Capture_zpsasuitutq.png[/IMG][/URL]

**Comment by ospalh** [comment]
>Can I choose to have audio download only from Merriam Webster?

Change [the list](https://github.com/ospalh/anki-addons/blob/master/downloadaudio/downloaders/__init__.py#L39-L54) in [`downloadaudio/downloaders/__init__.py`](https://github.com/ospalh/anki-addons/blob/master/downloadaudio/downloaders/__init__.py). Also RT[FM](http://ospalh.github.io/anki-addons/Downloader%20sites.html#sitesonoff)

> Or, at least have all the audios unticked by default.

Set the standard value from `Action.Add` in [line 31 of `download_entry.py`](https://github.com/ospalh/anki-addons/blob/master/downloadaudio/download_entry.py#L31) to `Action.Delete`. Then you can set the action to `Action.Add` in `mw.py`, after [lines 129](https://github.com/ospalh/anki-addons/blob/master/downloadaudio/downloaders/mw.py#L129). Take a look at [google_tts.py](https://github.com/ospalh/anki-addons/blob/master/downloadaudio/downloaders/google_tts.py#L57), how it is witched to delete there.
