### ISSUE TITLE
eSpeak support

### ISSUE THREAD

**Issue by aleksejrs** [ospalh/anki-addons#58]
"[eSpeak](http://espeak.sourceforge.net/) is a … speech synthesizer for English and other languages, for Linux and Windows. … ported to other platforms … Can produce speech output as a WAV file."

Can speak English almost as good as Google TTS, and is local and configurable.

**Comment by ospalh** [comment]
I think i will drop Google TTS again…
The real point of this is to get *good* pronunciations, spoken by real humans.
If you want computer voices, try [Awesom TTS](https://ankiweb.net/shared/info/301952613). That even lists eSpeak on the download page.
