### ISSUE TITLE
Scroll bar in Mac OSX Yosemite 10.10.2

### ISSUE THREAD

**Issue by tuanmh** [ospalh/anki-addons#66]
It would be great if you can add a scroll bar in Mac OSX Yosemite 10.10.2. Currently, I cannot add audio as shown in the image. 

![image](https://cloud.githubusercontent.com/assets/3193353/6773546/c568b648-d166-11e4-9cc7-d8ca9e894cc9.png)

**Comment by ospalh** [comment]
It’s not only on Macs. Although there, for some reason, it uses more padding so you run into it earlier there.

**Comment by ospalh** [comment]
I just released v 3.1.0.
Please download the new version. ID 3100585138

**Comment by tuanmh** [comment]
Works like champ, thanks mate!
