### ISSUE TITLE
open anki to specific deck

### ISSUE THREAD

**Issue by DrLulz** [ospalh/anki-addons#67]
My question is unrelated to your addons, so I apologize in advance for asking here.
  
When opening Anki I would like to open it to a specific deck. Is it possible to execute the application with a deck name/did as the argument, or possibly within the anki module?

best regards,

**Comment by ospalh** [comment]
>My question is unrelated to your addons, so I apologize in advance for asking here.

Try this [add-ons discussion](https://anki.tenderapp.com/discussions/add-ons) forum.

> (…) specific deck (…)

I don't think so. Would probably require a new add-on (that i’m not interested in).
