### ISSUE TITLE
default action should be "delete" instead of "add"

### ISSUE THREAD

**Issue by Twilight** [ospalh/anki-addons#71]
Usually the user intends to keep only one of them, this will save a lot of clicks.

**Comment by ospalh** [comment]
I usually keep more than one.
And switching *all* to delete will confuse people. “The download worked, but there is *still* no sound on the card."
Maybe i will change it so that only the first download gets an add. But probably not.

**Comment by Twilight** [comment]
then prompt if none selected on "OK"

**Comment by ospalh** [comment]
Too much work
