### ISSUE TITLE
Collins pronunciations are not available anymore

### ISSUE THREAD

**Issue by mnix-xinm** [ospalh/anki-addons#73]
download_audio plugin

Pronunciations from Collins at least for Spanish and German are not available anymore.

Thanks in advance.

Anki Versión 2.0.32
Qt 4.8.6 PyQt 4.11.2

Debian GNU/Linux Stable (8.2)

Latest version of download_audio (I presume it's 3.10.0 at the moment).

**Comment by ospalh** [comment]
I see what you mean, i will have a look at this.
But i never liked the Collins pronunciations much. I think they are TTS (robot voices). When this is something that is easy to fix, i will do it, but if it requires a longer rework, i may drop the Collins downloaders instead.

**Comment by mnix-xinm** [comment]
That would be very unfortunate. There are not so many sources of pronunciation for Spanish and Collins's sounds are good enough for me.

**Comment by blacktea** [comment]
Yes, Collins's was the best compared to others.

**Comment by blacktea** [comment]
It seems now they have separated MP3 for each word

```
<h1 class="orth h1_entry">cuarenta<span class="hwd_sound">    <a class="hwd_sound sound audio_play_button" title="Pronunciation for " data-src-mp3="/sounds/e/es_/es_41/es_419_w0034280.mp3"></a>
</span></h1>
```

**Comment by ospalh** [comment]
Fixed. Please get v4.1.0 with the add-on id 3100585138.
