### ISSUE TITLE
[request] play_button to play one audio on every keyboard button click

### ISSUE THREAD

**Issue by omega3** [ospalh/anki-addons#74]
Hi, 
Thank you for excellent add-on play_button. I works very well with mouse. 

But recently I remaped audio button (R) to plus key following your advice here
https://anki.tenderapp.com/discussions/add-ons/4752-remap-replay-audio-button-to-space-bar
and I had an idea that would be great if I could do the same without using mouse but only keyboard.

Would it be possible for you to add a new feature to it or create new add-on that would play one audio file on every keyboard button click? 
I mean: when I have several audio files on one note and I use + key, they are played one after another automatically. This sometimes is too quick and doesn't allow me to follow text or repeat aloud. So I am forced to use mouse/touchpad anyway. 
Being able to use + key to play them one at a time (still being at the same note/card) would solve the necessity of using mouse/touchpad.

**Comment by ospalh** [comment]
This would be somewhat complicated.
I don't think i will do it, at least not any time soon.
Maybe this is an opportunity for you to learn Python programming and do this yourself. :wink:

**Comment by omega3** [comment]
I don't require this anymore so I close it.
