### ISSUE TITLE
"Quick note and deck buttons"  - second row?

### ISSUE THREAD

**Issue by kiuuik** [ospalh/anki-addons#93]
"Quick note and deck buttons" is fantastic. My question is: How to modify the addon so that it uses two lines?

My motivation: Since I bought a notebook with a scmall screen I have to make my Anki Add window quite narrow so that I can fit my other essential windows. Since then I can only see one or two letters on my quick buttons and the buttons are so narrow that I regularly click off target. But I have enough space vertically in my Anki Add window. So a second row for your buttons would be great or maybe all your buttons could be optionally pushed to this second row so that they don't have to share space with the built-in "Note type"/Deck chooser .

I already use as few decks as possible.

PS: Your addons are a great help. Thanks a lot!

**Comment by ospalh** [comment]
Sorry, this is not how this add-on works. It doesn’t really concern itself with the layout of that button bar. It only adds the extra buttons to the old-style one, and, in a way, doesn’t know or care about where these buttons end up. You would have to look at other bits of the Anki code itself, and write your own add-on. (I’m not interested in this one, sorry.) Starting points are, probably, [`addcards.ui`](https://github.com/dae/anki/blob/master/designer/addcards.ui) and [`addcards.py`](https://github.com/dae/anki/blob/master/aqt/addcards.py).
