### ISSUE TITLE
Play button doesn't work for certain filenames

### ISSUE THREAD

**Issue by aleixosk** [ospalh/anki-addons#96]
The play button currently stays mute for certain files containing special characters such as `&` and `%` in their name. 

From what I've observed, there are two reasons for this behaviour. The first is that when we get the filename, it's been escaped for HTML, which obviously breaks it for us because we're passing it to a function rather than embedding it (so `&` becomes `&amp;`). Secondly, our link handler takes a URL as a parameter, which means that the filename should also be escaped as such. Otherwise, if the filename contains any percent-encoded character (which is very likely if the files have been scraped from a website), this will be unencoded and the link will point to the wrong location (`%25` would become `%`).

On a side note, I don't know what the last line (`<span style="display: none;">&#91;sound:{fn}&#93;</span>`) in the button code is supposed to achieve, since the original embedded sound is already present right at the beginning and the add-on even works like a charm without it. Also, this would take a different encoding than in the first case.

I've had a look at the code and done my best to fix it, and I'd be more than happy to try and do a pull request (which would also be my first ever :)). However, I don't reaally know what I'm doing so I figured I'd better discuss it first.

**Comment by ospalh** [comment]
Thanks for the report, I’ll look into this, too.

You say you’ve done some work on this.
I don’t see you having forked the repo here on github. That’s one step you have to do before you can open a pull request.
Pushing your work to github, even without a pull request, is the easiest way for me to see your work, and avoiding rewriting it, too.

>I don't know what the last line (<span style="display: none;">&#91;sound:{fn}&#93;</span>) in the button code is supposed to achieve, 

It’s to show the file name in the card browser.

>the add-on even works like a charm without it.

For the card browser display, i’ll interpreted this in the Penn & Teller way “Works like a charm. That’s to say, not at all!” (Approximate quote from one episode of Bullshit!)

**Comment by aleixosk** [comment]
Thanks for letting me know, I just pushed what I'd done. Sorry for taking so long!

I still haven't been able to figure out what that line changes in the card browser, so I  just haven't touched it for now. I'll also definitely be looking for a chance to use that comeback in the future.

**Comment by ospalh** [comment]
I guess i’ll do some tests, but this looks good at first glance. Thanks.

Re the browser:
I cba to post screen shots, but for example when you use only sound/video in the question, standard Anki then shows an empty field in the “Question” column, with the add-on you get the file name there.

**Comment by ospalh** [comment]
As i suspected, this whole situation is a bit complicated, and hard to test. It’s somewhat tricky to get sounds with plain ampersands (“&”s) into the card.
Anki changes`&` to `&amp;`, even when you use the “HTML Editor”. Not sure if you should call it a limitation or a bug.

Try this: 
* Make sure you have the file with a plain `&`
* Find the card in the card browser
* Open the HTML Editor for the field with the sound file (Select field, Ctrl+Shift+X)
* Close it
* Open it again
* Anki has changed the text.

![_ _](https://cloud.githubusercontent.com/assets/1690429/21885146/aece9052-d8b6-11e6-8171-8eb53709d920.png)
![_ amp _](https://cloud.githubusercontent.com/assets/1690429/21885149/b274b09c-d8b6-11e6-97b0-720cb0e8a3e6.png)

**Comment by ospalh** [comment]
I’ll have to think about what the Right Thing is here.
Maybe it’s to just say that plain `&`s in file names are unsupported.

I’ll have to take a look at `%` and the other “forbidden” (in HTML) characters. (Although i guess fewer people use “`<`” in file names.)

**Comment by aleixosk** [comment]
I don't think that's really a bug (nor a limitation). The value saved in the field will actually be the correct one, it's just that since you're editing HTML ampersands are escaped. In any case, that would be Anki's fault and not yours.

For me editing file names in the HTML editor works nicely (taking that into account) and so does the play button. I think that the encoding is handled properly now but please let me know if you find any issues.

`<` and `>` are restricted characters on Windows, and ugly as hell in a filename on Linux.
